name = "webfinger-viewer-worker"
main = "webfinger-viewer-worker/build/worker/shim.mjs"
compatibility_date = "2026-07-02"

[build]
command = "scripts/build-webfinger-viewer-worker.sh"

[observability]
enabled = true
