[package]
name = "webfinger-rs"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
keywords.workspace = true
authors.workspace = true
readme.workspace = true

[features]
reqwest = ["dep:reqwest"]

[dependencies]
http.workspace = true
percent-encoding = "2.3.1"
nutype = { version = "0.5.0", features = ["serde"] }
reqwest = { version = "0.12.7", optional = true, features = ["json"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_with = "3.9.0"
thiserror = "1.0.64"
tracing = "0.1.40"
url = "2.5.2"
