[package]
name = "webfinger-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
keywords.workspace = true
authors.workspace = true

[features]
#! ## Features
#!
## No features are enabled by default.
default = []

## Provides integration with the Actix web framework.
actix = ["dep:actix-web"]
## Provides integration with the Axum web framework.
axum = ["dep:axum", "dep:axum-extra"]
## Provides integration with the Reqwest HTTP client.
reqwest = ["dep:reqwest"]

[dependencies]
actix-web = { workspace = true, optional = true }
async-convert = "1.0.0"
axum = { workspace = true, optional = true, features = ["json"] }
axum-extra = { version = "0.10.0", optional = true, features = ["query"] }
document-features = "0.2.11"
http.workspace = true
nutype = { version = "0.6.1", features = ["serde"] }
percent-encoding = "2.3.1"
reqwest = { workspace = true, optional = true, features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_with = "3.12.0"
tracing.workspace = true
thiserror = "2.0.12"

[dev-dependencies]
actix-web = { workspace = true, features = ["rustls-0_23"] }
actix-tls = { version = "3.4.0", features = ["rustls-0_23"] }
axum = { workspace = true, default-features = true }
color-eyre.workspace = true
http-body-util = "0.1.3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["trace"] }
rcgen = "0.13.2"
rustls = "0.23.25"
axum-server = { version = "0.7.2", features = ["tls-rustls"] }

[package.metadata.docs.rs]
all-features = true
# see https://doc.rust-lang.org/nightly/rustdoc/scraped-examples.html
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]


[[example]]
name = "axum"
required-features = ["axum"]
doc-scrape-examples = true

[[example]]
name = "actix"
required-features = ["actix"]

[[example]]
name = "client"
required-features = ["reqwest"]
