[package]
name = "webfinger-cli"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
keywords.workspace = true
authors.workspace = true
readme.workspace = true

[dependencies]
http.workspace = true

clap = { version = "4.5.18", features = ["derive"] }
color-eyre.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
tracing-error.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
webfinger-rs = { workspace = true, features = ["reqwest"] }

[[bin]]
name = "webfinger"
path = "src/main.rs"
