[package]
name = "webfinger-cli"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
keywords.workspace = true
authors.workspace = true
readme.workspace = true

[dependencies]
http.workspace = true

clap = { version = "4.5.18", features = ["derive"] }
color-eyre = "0.6.3"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
webfinger-rs = { workspace = true, features = ["reqwest"] }

[[bin]]
name = "webfinger"
path = "src/main.rs"
